// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exouqmqaqcviacowebaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4b3VxbXFhcWN2aWFjb3dlYmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1Mjk2MDQsImV4cCI6MjA4ODEwNTYwNH0.OOS67_ziUTREdiBAk841WrHXM7uLcDss-848puxIW9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});